UI/EIP.Web/Areas/System/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using EIP.Common.Web;
using EIP.System.Business.Config;
using EIP.System.Models.Entities;

namespace EIP.Web.Areas.System.Controllers
{
    public class CalendarController : BaseController
    {
        /// <summary>
        /// 我的日历
        /// </summary>
        /// <returns></returns>
        public async Task<ViewResultBase> MyCalendar()
        {
            var format = new CalendarViewFormat(CalendarViewType.week, DateTime.Now, DayOfWeek.Monday);
            return View((await _calendarLogic.QueryCalendars(format.StartDate, format.EndDate, CurrentUser.UserId)).ToList());
        }
        
        /// <summary>
        /// 日历详情
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<ViewResultBase> ViewCalendar(int? id)
        {
            SystemCalendar calendar = id.HasValue ? await _calendarLogic.GetByIdAsync((id.Value)) : new SystemCalendar();
            return View(calendar);
        }

        /// <summary>
        /// 编辑日历
        /// </summary>
        /// <param name="id"></param>
        /// <param name="start"></param>
        /// <param name="end"></param>
        /// <param name="isallday"></param>
        /// <returns></returns>
        public async Task<ViewResultBase> EditCalendar(int? id,
            string start,
            string end,
            int? isallday)
        {
            SystemCalendar calendar;
            if (id.HasValue && id > 0)
            {
                calendar = await _calendarLogic.GetByIdAsync(id.Value);
                int clientzone = calendar.MasterId.HasValue ? calendar.MasterId.Value : 8;
                int serverzone = TimeHelper.GetTimeZone();
                var zonediff = clientzone - serverzone;
                //时区转换
                calendar.StartTime = calendar.StartTime.AddHours(zonediff);
                calendar.EndTime = calendar.EndTime.AddHours(zonediff);
            }
            else
            {
                calendar = new SystemCalendar();
                calendar.StartTime = Convert.ToDateTime(start);
                calendar.EndTime = Convert.ToDateTime(end);
                calendar.IsAllDayEvent = isallday.HasValue && isallday.Value == 1;

            }
            return View(calendar);
        }

        /// <summary>
        /// 保存日历
        /// </summary>
        /// <param name="id">The id.</param>
        /// <param name="form">The form.</param>
        /// <returns></returns>
        [AcceptVerbs(HttpVerbs.Post)]
        public async Task<JsonResult> SaveCalendar(int id, FormCollection form)
        {
            JsonReturnMessages r = new JsonReturnMessages();
            try
            {
                SystemCalendar data;
                if (id > 0)
                {
                    data = await _calendarLogic.GetByIdAsync(id);
                }
                else
                {
                    data = new SystemCalendar();
                }
                data.Subject = form["Subject"];
                data.Location = form["Location"];
                data.Description = form["Description"];
                data.IsAllDayEvent = form["IsAllDayEvent"] != "false";
                data.Category = form["colorvalue"];
                string sdate = form["stpartdate"];
                string edate = form["etpartdate"];
                string stime = form["stparttime"];
                string etime = form["etparttime"];
                int clientzone = Convert.ToInt32(form["timezone"]);
                int serverzone = TimeHelper.GetTimeZone();
                var zonediff = serverzone - clientzone;

                if (data.IsAllDayEvent)
                {
                    data.StartTime = Convert.ToDateTime(sdate).AddHours(zonediff);
                    data.EndTime = Convert.ToDateTime(edate).AddHours(23).AddMinutes(59).AddSeconds(59).AddHours(zonediff);
                }
                else
                {
                    data.StartTime = Convert.ToDateTime(sdate + " " + stime).AddHours(zonediff);
                    data.EndTime = Convert.ToDateTime(edate + " " + etime).AddHours(zonediff);
                }
                if (data.EndTime <= data.StartTime)
                {
                    throw new Exception("开始时间不能大于结束时间");
                }
                data.CalendarType = 1;
                data.InstanceType = 0;
                data.MasterId = clientzone;
                data.UPAccount = CurrentUser.UserId;
                data.UPName = CurrentUser.Name;
                data.UPTime = DateTime.Now;

                if (data.Id > 0)
                {
                    await _calendarLogic.UpdateAsync(data);
                }
                else
                {
                    await _calendarLogic.InsertAsync(data);
                }
                r.IsSuccess = true;
                r.Msg = "操作成功!";
            }
            catch (Exception ex)
            {
                r.IsSuccess = false;
                r.Msg = ex.Message;
            }
            return Json(r);
        }

        /// <summary>
        /// 快速删除个人日程
        /// </summary>
        /// <param name="form">The form.</param>
        /// <returns></returns>
        [AcceptVerbs(HttpVerbs.Post)]
        public async Task<JsonResult> QuickDeletePersonalCal(FormCollection form)
        {
            JsonReturnMessages r = new JsonReturnMessages();
            string id = form["calendarId"];
            if (string.IsNullOrEmpty(id))
            {
                r.IsSuccess = false;
                r.Msg = "参数id无效";
                return Json(r);
            }
            try
            {
                await _calendarLogic.DeleteAsync(Convert.ToInt32(id));
                r.IsSuccess = true;
                r.Msg = "操作成功!";
            }
            catch (Exception ex)
            {
                r.IsSuccess = false;
                r.Msg = ex.Message;
            }
            return Json(r);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="form"></param>
        /// <returns></returns>
        [AcceptVerbs(HttpVerbs.Post)]
        public async Task<string> GetPersonalCalViewData(FormCollection form)
        {
            CalendarViewType viewType = (CalendarViewType)Enum.Parse(typeof(CalendarViewType), form["viewtype"]);
            string strshowday = form["showdate"];
            DateTime showdate;
            int clientzone = Convert.ToInt32(form["timezone"]);
            int serverzone = TimeHelper.GetTimeZone();
            var zonediff = serverzone - clientzone;
            bool b = DateTime.TryParse(strshowday, out showdate);
            var jss = new JavaScriptSerializer();
            jss.MaxJsonLength = Int32.MaxValue;//增加最大长度
            if (!b)
            {
                var ret = new JsonCalendarViewData(new JsonError("NotVolidDateTimeFormat", "错误的时间格式"));
                return jss.Serialize(ret);
            }
            var format = new CalendarViewFormat(viewType, showdate, DayOfWeek.Monday);
            var qstart = format.StartDate.AddHours(zonediff);
            var qend = format.EndDate.AddHours(zonediff);
            List<SystemCalendar> list = (await _calendarLogic.QueryCalendars(qstart, qend, CurrentUser.UserId)).ToList();
            var data = new JsonCalendarViewData(ConvertToStringArray(list), format.StartDate, format.EndDate);
            return jss.Serialize(data);
        }

        /// <summary>
        /// 快速新增
        /// </summary>
        /// <param name="form">The form.</param>
        /// <returns></returns>
        [AcceptVerbs(HttpVerbs.Post)]
        public async Task<JsonResult> QuickAddPersonalCal(FormCollection form)
        {
            JsonReturnMessages r = new JsonReturnMessages();
            string subject = form["CalendarTitle"];
            string strStartTime = form["CalendarStartTime"];
            string strEndTime = form["CalendarEndTime"];
            string isallday = form["IsAllDayEvent"];
            int clientzone = Convert.ToInt32(form["timezone"]);
            int serverzone = TimeHelper.GetTimeZone();
            var zonediff = serverzone - clientzone;
            DateTime st;
            DateTime et;

            bool a = DateTime.TryParse(strEndTime, out et);
            bool b = DateTime.TryParse(strStartTime, out st);
            if (!b)
            {
                r.IsSuccess = false;
                r.Msg = "错误的时间格式" + ":" + strStartTime;
                return Json(r);
            }
            if (!a)
            {
                r.IsSuccess = false;
                r.Msg = "错误的时间格式" + ":" + strEndTime;
                return Json(r);
            }

            try
            {
                SystemCalendar entity = new SystemCalendar();
                entity.CalendarType = 1;
                entity.InstanceType = 0;
                entity.Subject = subject;
                entity.StartTime = st.AddHours(zonediff);
                entity.EndTime = et.AddHours(zonediff);
                entity.IsAllDayEvent = isallday == "1";
                entity.UPAccount = CurrentUser.UserId;
                entity.UPName = CurrentUser.Name;
                entity.UPTime = DateTime.Now;
                entity.MasterId = clientzone;
                r.Data = (await _calendarLogic.InsertScalarAsync(entity)).Data;
                r.IsSuccess = true;
                r.Msg = "操作成功!";
            }
            catch (Exception ex)
            {
                r.IsSuccess = false;
                r.Msg = ex.Message;
            }
            return Json(r);
        }

        /// <summary>
        /// 快速更新
        /// </summary>
        /// <param name="form">The form.</param>
        /// <returns></returns>
        [AcceptVerbs(HttpVerbs.Post)]

UI/EIP.Web/Areas/System/Views/Calendar/EditCalendar.cshtml
@{
    Layout = null;
}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
@model EIP.System.Models.Entities.SystemCalendar
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=7" />
    <title>修改日程详细</title>
    <link href="/Scripts/lib/xgcalendar/Theme/Default/main.css" rel="stylesheet" type="text/css" />
    <link href="/Scripts/lib/xgcalendar/Theme/Default/dp.css" rel="stylesheet" />
    <link href="/Scripts/lib/xgcalendar/Theme/Default/dropdown.css" rel="stylesheet" />
    <link href="/Scripts/lib/xgcalendar/Theme/Default/colorselect.css" rel="stylesheet" />
    <style type="text/css">
        .calpick {
            width: 25px;
            border: none;
            cursor: pointer;
            background: url("/Scripts/lib/xgcalendar/images/icons/cal.gif") no-repeat center 2px;
            margin-left: -22px;
        }
    </style>
</head>
<body>
    <div>
        <div class="toolBotton">
            <a id="Savebtn" class="imgbtn" href="javascript:void(0);">
                <span class="Save" title="保存">保存(<u>S</u>)</span>
            </a>
            @{
                if (Model.Id > 0)
                {<a id="Deletebtn" class="imgbtn" href="javascript:void(0);">
                    <span class="Delete" title="取消该日程">删除(<u>D</u>)</span>
                </a>
                }
            }
            <a id="Closebtn" class="imgbtn" href="javascript:void(0);">
                <span class="Close" title="关闭窗口">关闭</span>
            </a>
        </div>
        <div style="clear: both">
        </div>
        <div class="infocontainer">
            @{
                using (Html.BeginForm("SaveCalendar", "Calendar", new { id = Model.Id }, FormMethod.Post, new { id = "fmEdit", @class = "fform" }))
                {
                    <label>
                        <span>
                            *主题：
                        </span>
                        <div id="calendarcolor"></div>
                        @Html.TextBox("Subject", Model.Subject, new { style = "width:85%;", @class = "required safe", MaxLength = "200" })
                        @Html.Hidden("colorvalue", Model.Category)
                    </label>
                    <label>
                        <span>
                            *时间：
                        </span>
                        <div>
                            @Html.TextBox("stpartdate", Model.StartTime > DateTime.MinValue ? Model.StartTime.ToString("yyyy-M-d") : "", new { @class = "required date", style = "padding-left:2px;width:90px;", MaxLength = "10" })
                            @Html.TextBox("stparttime", Model.StartTime > DateTime.MinValue ? Model.StartTime.ToString("HH:mm") : "", new { @class = "required time", style = "width:40px;", MaxLength = "5" })
                            到
                            @Html.TextBox("etpartdate", Model.EndTime > DateTime.MinValue ? Model.EndTime.ToString("yyyy-M-d") : "", new { @class = "required date", style = "padding-left:2px;width:90px;", MaxLength = "10" })
                            @Html.TextBox("etparttime", Model.EndTime > DateTime.MinValue ? Model.EndTime.ToString("HH:mm") : "", new { @class = "required time", style = "width:40px;", MaxLength = "50" })

                            <label class="checkp">
                                @Html.CheckBox("IsAllDayEvent", Model.IsAllDayEvent)
                                全天日程
                            </label>
                        </div>
                    </label>

                    <label>
                        <span>
                            地点：
                        </span>
                        @Html.TextBox("Location", Model.Location, new { style = "width:95%;", MaxLength = "200" })
                    </label>
                    <label>
                        <span>
                            备注：
                        </span>
                        @Html.TextArea("Description", Model.Description, new { style = "width:95%; height:70px" })
                    </label>
                    @Html.Hidden("timezone")
                }
            }
        </div>
        <script src="/Scripts/lib/xgcalendar/Javascripts/jquery.min.js" type="text/javascript"></script>
        <script src="/Scripts/lib/xgcalendar/Javascripts/Common.js" type="text/javascript"></script>
        <script src="/Scripts/lib/xgcalendar/Javascripts/Plugins/jquery.form.js" type="text/javascript"></script>
        <script src="/Scripts/lib/xgcalendar/Javascripts/Plugins/jquery.validate.js" type="text/javascript"></script>
        <script src="/Scripts/lib/xgcalendar/Javascripts/Plugins/datepicker_lang_zh_CN.js" type="text/javascript"></script>
        <script src="/Scripts/lib/xgcalendar/Javascripts/Plugins/jquery.datepicker.js" type="text/javascript"></script>
        <script src="/Scripts/lib/xgcalendar/Javascripts/Plugins/jquery.dropdown.js" type="text/javascript"></script>
        <script src="/Scripts/lib/xgcalendar/Javascripts/Plugins/jquery.colorselect.js" type="text/javascript"></script>
        <script type="text/javascript">
            if (!DateAdd || typeof (DateDiff) != "function") {
                var DateAdd = function (interval, number, idate) {
                    number = parseInt(number);
                    var date;
                    if (typeof (idate) == "string") {
                        date = idate.split(/\D/);
                        eval("var date = new Date(" + date.join(",") + ")");
                    }
                    if (typeof (idate) == "object") {
                        date = new Date(idate.toString());
                    }
                    switch (interval) {
                        case "y": date.setFullYear(date.getFullYear() + number); break;
                        case "m": date.setMonth(date.getMonth() + number); break;
                        case "d": date.setDate(date.getDate() + number); break;
                        case "w": date.setDate(date.getDate() + 7 * number); break;
                        case "h": date.setHours(date.getHours() + number); break;
                        case "n": date.setMinutes(date.getMinutes() + number); break;
                        case "s": date.setSeconds(date.getSeconds() + number); break;
                        case "l": date.setMilliseconds(date.getMilliseconds() + number); break;
                    }
                    return date;
                }
            }
            function getHM(date) {
                var hour = date.getHours();
                var minute = date.getMinutes();
                var ret = (hour > 9 ? hour : "0" + hour) + ":" + (minute > 9 ? minute : "0" + minute);
                return ret;
            }
            $(document).ready(function () {
                //debugger;
                var arrT = [];
                var tt = "{0}:{1}";
                for (var i = 0; i < 24; i++) {
                    arrT.push({ text: StrFormat(tt, [i >= 10 ? i : "0" + i, "00"]) }, { text: StrFormat(tt, [i >= 10 ? i : "0" + i, "30"]) });
                }
                $("#timezone").val(new Date().getTimezoneOffset() / 60 * -1);
                $("#stparttime").dropdown({
                    dropheight: 200,
                    dropwidth: 60,
                    selectedchange: function () { },
                    items: arrT
                });
                $("#etparttime").dropdown({
                    dropheight: 200,
                    dropwidth: 60,
                    selectedchange: function () { },
                    items: arrT
                });
                var check = $("#IsAllDayEvent").click(function (e) {
                    if (this.checked) {
                        $("#stparttime").val("00:00").hide();
                        $("#etparttime").val("00:00").hide();
                    }
                    else {
                        var d = new Date();
                        var p = 60 - d.getMinutes();
                        if (p > 30) p = p - 30;
                        d = DateAdd("n", p, d);
                        $("#stparttime").val(getHM(d)).show();
                        $("#etparttime").val(getHM(DateAdd("h", 1, d))).show();
                    }
                });
                if (check[0].checked) {
                    $("#stparttime").val("00:00").hide();
                    $("#etparttime").val("00:00").hide();
                }
                $("#Savebtn").click(function () { $("#fmEdit").submit(); });
                $("#Closebtn").click(function () { CloseModelWindow(); });
                $("#Deletebtn").click(function () {
                    if (confirm("你确定要取消该日程吗？")) {
                        var param = [{ "name": "calendarId", value: @Model.Id }];
                        $.post("/System/Calendar/QuickDeletePersonalCal",
                            param,
                            function (data) {
                                if (data.IsSuccess) {
                                    alert(data.Msg);
                                    CloseModelWindow(null, true);
                                }
                                else {
                                    alert("操作失败：\r\n" + data.Msg);
                                }
                            }
                        , "json");
                    }
                });

                $("#stpartdate,#etpartdate").datepicker({ picker: "<button class='calpick'></button>" });
                var cv = $("#colorvalue").val();
                if (cv == "") {
                    cv = "-1";
                }
                $("#calendarcolor").colorselect({ title: "颜色分类", index: cv, hiddenid: "colorvalue" });
                //定义ajaxform的调用参数
                var options = {
                    beforeSubmit: function () {
                        return true;
                    },
                    dataType: "json",
                    success: function (data) {
                        alert(data.Msg);
                        if (data.IsSuccess) {
                            CloseModelWindow(null, true);
                        }
                    }
                };
                $.validator.addMethod("date", function (value, element) {
                    var arrs = value.split(i18n.datepicker.dateformat.separator);
                    var year = arrs[i18n.datepicker.dateformat.year_index];
                    var month = arrs[i18n.datepicker.dateformat.month_index];
                    var day = arrs[i18n.datepicker.dateformat.day_index];
                    var standvalue = [year, month, day].join("-");
                    return this.optional(element) || /^(?:(?:1[6-9]|[2-9]\d)?\d{2}[\/\-\.](?:0?[1,3-9]|1[0-2])[\/\-\.](?:29|30))(?: (?:0?\d|1\d|2[0-3])\:(?:0?\d|[1-5]\d)\:(?:0?\d|[1-5]\d)(?: \d{1,3})?)?$|^(?:(?:1[6-9]|[2-9]\d)?\d{2}[\/\-\.](?:0?[1,3,5,7,8]|1[02])[\/\-\.]31)(?: (?:0?\d|1\d|2[0-3])\:(?:0?\d|[1-5]\d)\:(?:0?\d|[1-5]\d)(?: \d{1,3})?)?$|^(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])[\/\-\.]0?2[\/\-\.]29)(?: (?:0?\d|1\d|2[0-3])\:(?:0?\d|[1-5]\d)\:(?:0?\d|[1-5]\d)(?: \d{1,3})?)?$|^(?:(?:16|[2468][048]|[3579][26])00[\/\-\.]0?2[\/\-\.]29)(?: (?:0?\d|1\d|2[0-3])\:(?:0?\d|[1-5]\d)\:(?:0?\d|[1-5]\d)(?: \d{1,3})?)?$|^(?:(?:1[6-9]|[2-9]\d)?\d{2}[\/\-\.](?:0?[1-9]|1[0-2])[\/\-\.](?:0?[1-9]|1\d|2[0-8]))(?: (?:0?\d|1\d|2[0-3])\:(?:0?\d|[1-5]\d)\:(?:0?\d|[1-5]\d)(?:\d{1,3})?)?$/.test(standvalue);
                }, "输入的日期格式不正确");
                $.validator.addMethod("time", function (value, element) {
                    return this.optional(element) || /^([0-1]?[0-9]|2[0-3]):([0-5][0-9])$/.test(value);
                }, "输入的时间格式不正确");
                $.validator.addMethod("safe", function (value, element) {
                    return this.optional(element) || /^[^$\<\>]+$/.test(value);
                }, "不能包含以下符号: $<>");
                $("#fmEdit").validate({
                    submitHandler: function (form) { $("#fmEdit").ajaxSubmit(options); },
                    errorElement: "div",
                    errorClass: "cusErrorPanel",
                    errorPlacement: function (error, element) {
                        showerror(error, element);
                    }
                });
                function showerror(error, target) {
                    var pos = target.position();
                    var height = target.height();
                    var newpos = { left: pos.left, top: pos.top + height + 2 }
                    var form = $("#fmEdit");
                    error.appendTo(form).css(newpos);
                }
            });
        </script>
    </div>
</body>
</html>

UI/EIP.Web/Areas/System/Views/Calendar/ViewCalendar.cshtml
@{
   
    Layout =null;
}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>ViewCalendar</title>
</head>
<body>
    <div>
        待建中...
    </div>
</body>
</html>